# 文本处理配置
max_width: 78

# 语言设置
# 可选值：
#   - auto: 自动检测语言（推荐）
#   - en: 英语
#   - zh: 中文
#   注：目前主要支持英语和中文，其他语言可能需要额外安装语言模型
language: en

# 语言模型大小
# 可选值：
#   - sm: 小型模型（约50MB），速度快，准确度一般
#   - md: 中型模型（约100MB），速度和准确度均衡（推荐）
#   - lg: 大型模型（约500MB），速度慢，准确度高
# 注意：
#   1. 首次使用需要下载模型，例如：
#      python -m spacy download en_core_web_md
#   2. 如果使用中文，也需要下载对应的中文模型：
#      python -m spacy download zh_core_web_md
model_size: md

# 文件路径配置
input_file: data/input/Agentic AI applications.txt
output_file: data/output/{timestamp}-{input_file_basename}.txt

# 调试配置
debug:
  enabled: false
  temp_dir: data/debug  # 临时文件目录
