# Default Plugin Chain Configuration

[plugins]
# Plugin execution order
order = ["builtin/punctuation_adder", "builtin/sentence_splitter"]

# Plugin-specific configurations
[plugin_configs."builtin/punctuation_adder"]
enabled = true
model_name = "oliverguhr/fullstop-punctuation-multilang-large"
replace_dashes = true
split_sentences = false
capitalize_sentences = false

[plugin_configs."builtin/sentence_splitter"]
enabled = true
min_recursive_length = 70
max_depth = 8
max_degradation_round = 5