[plugins]
# 插件链配置（引用默认插件链）
current_plugin_chain = "default_plugin_chain.toml"

[paths]
# 输入文件路径：
# - 留空则首次运行会提示输入
# - 相对路径基于 data/input/ 目录
input_file = ""
# 输出文件路径：保持为空；由 GUI 根据输入与“Add timestamp”选项生成建议
output_file = ""

[output]
# Whether to prefix output filename with timestamp when auto-suggesting
add_timestamp = true

[debug]
# 是否启用调试输出（生成中间结果与日志）
enabled = false
# 调试文件输出目录
debug_dir = "data/debug"

[logging]
# 日志级别: DEBUG, INFO, WARNING, ERROR
# DEBUG: 显示所有日志（包括调试信息）
# INFO: 显示普通信息和警告错误（推荐）
# WARNING: 只显示警告和错误
# ERROR: 只显示错误
level = "INFO"