[plugins]
order = [
    "builtin/punctuation_adder",
    "builtin/text_to_sentences",
    "builtin/sentence_splitter",
]

[plugin_configs."builtin/punctuation_adder"]
enabled = true
replace_dashes = true
split_sentences = false
capitalize_sentences = true

[plugin_configs."builtin/sentence_splitter"]
enabled = true
min_recursive_length = 70
max_depth = 8
max_degradation_round = 5

[plugin_configs."builtin/text_to_sentences"]
enabled = true
sentence_endings = [
    ".",
    "!",
    "?",
]
abbreviation_patterns = [
    "Mr.",
    "Mrs.",
    "Dr.",
    "Prof.",
    "Inc.",
    "Ltd.",
    "Co.",
    "Corp.",
    "st.",
]
normalize_whitespace = true
remove_empty_sentences = true
filter_ellipsis_only = false
